// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1beta1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v3/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// TokenReview attempts to authenticate a token to a known user. Note: TokenReview requests may be cached by the webhook token authenticator plugin in the kube-apiserver.
type TokenReviewType struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string            `pulumi:"kind"`
	Metadata *metav1.ObjectMeta `pulumi:"metadata"`
	// Spec holds information about the request being evaluated
	Spec TokenReviewSpec `pulumi:"spec"`
	// Status is filled in by the server and indicates whether the request can be authenticated.
	Status *TokenReviewStatus `pulumi:"status"`
}

// TokenReviewTypeInput is an input type that accepts TokenReviewTypeArgs and TokenReviewTypeOutput values.
// You can construct a concrete instance of `TokenReviewTypeInput` via:
//
//          TokenReviewTypeArgs{...}
type TokenReviewTypeInput interface {
	pulumi.Input

	ToTokenReviewTypeOutput() TokenReviewTypeOutput
	ToTokenReviewTypeOutputWithContext(context.Context) TokenReviewTypeOutput
}

// TokenReview attempts to authenticate a token to a known user. Note: TokenReview requests may be cached by the webhook token authenticator plugin in the kube-apiserver.
type TokenReviewTypeArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     pulumi.StringPtrInput     `pulumi:"kind"`
	Metadata metav1.ObjectMetaPtrInput `pulumi:"metadata"`
	// Spec holds information about the request being evaluated
	Spec TokenReviewSpecInput `pulumi:"spec"`
	// Status is filled in by the server and indicates whether the request can be authenticated.
	Status TokenReviewStatusPtrInput `pulumi:"status"`
}

func (TokenReviewTypeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*TokenReviewType)(nil)).Elem()
}

func (i TokenReviewTypeArgs) ToTokenReviewTypeOutput() TokenReviewTypeOutput {
	return i.ToTokenReviewTypeOutputWithContext(context.Background())
}

func (i TokenReviewTypeArgs) ToTokenReviewTypeOutputWithContext(ctx context.Context) TokenReviewTypeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TokenReviewTypeOutput)
}

// TokenReview attempts to authenticate a token to a known user. Note: TokenReview requests may be cached by the webhook token authenticator plugin in the kube-apiserver.
type TokenReviewTypeOutput struct{ *pulumi.OutputState }

func (TokenReviewTypeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*TokenReviewType)(nil)).Elem()
}

func (o TokenReviewTypeOutput) ToTokenReviewTypeOutput() TokenReviewTypeOutput {
	return o
}

func (o TokenReviewTypeOutput) ToTokenReviewTypeOutputWithContext(ctx context.Context) TokenReviewTypeOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o TokenReviewTypeOutput) ApiVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v TokenReviewType) *string { return v.ApiVersion }).(pulumi.StringPtrOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o TokenReviewTypeOutput) Kind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v TokenReviewType) *string { return v.Kind }).(pulumi.StringPtrOutput)
}

func (o TokenReviewTypeOutput) Metadata() metav1.ObjectMetaPtrOutput {
	return o.ApplyT(func(v TokenReviewType) *metav1.ObjectMeta { return v.Metadata }).(metav1.ObjectMetaPtrOutput)
}

// Spec holds information about the request being evaluated
func (o TokenReviewTypeOutput) Spec() TokenReviewSpecOutput {
	return o.ApplyT(func(v TokenReviewType) TokenReviewSpec { return v.Spec }).(TokenReviewSpecOutput)
}

// Status is filled in by the server and indicates whether the request can be authenticated.
func (o TokenReviewTypeOutput) Status() TokenReviewStatusPtrOutput {
	return o.ApplyT(func(v TokenReviewType) *TokenReviewStatus { return v.Status }).(TokenReviewStatusPtrOutput)
}

// TokenReview attempts to authenticate a token to a known user. Note: TokenReview requests may be cached by the webhook token authenticator plugin in the kube-apiserver.
type TokenReviewPatchType struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string            `pulumi:"kind"`
	Metadata *metav1.ObjectMeta `pulumi:"metadata"`
	// Spec holds information about the request being evaluated
	Spec *TokenReviewSpec `pulumi:"spec"`
	// Status is filled in by the server and indicates whether the request can be authenticated.
	Status *TokenReviewStatus `pulumi:"status"`
}

// TokenReviewPatchTypeInput is an input type that accepts TokenReviewPatchTypeArgs and TokenReviewPatchTypeOutput values.
// You can construct a concrete instance of `TokenReviewPatchTypeInput` via:
//
//          TokenReviewPatchTypeArgs{...}
type TokenReviewPatchTypeInput interface {
	pulumi.Input

	ToTokenReviewPatchTypeOutput() TokenReviewPatchTypeOutput
	ToTokenReviewPatchTypeOutputWithContext(context.Context) TokenReviewPatchTypeOutput
}

// TokenReview attempts to authenticate a token to a known user. Note: TokenReview requests may be cached by the webhook token authenticator plugin in the kube-apiserver.
type TokenReviewPatchTypeArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput `pulumi:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     pulumi.StringPtrInput     `pulumi:"kind"`
	Metadata metav1.ObjectMetaPtrInput `pulumi:"metadata"`
	// Spec holds information about the request being evaluated
	Spec TokenReviewSpecPtrInput `pulumi:"spec"`
	// Status is filled in by the server and indicates whether the request can be authenticated.
	Status TokenReviewStatusPtrInput `pulumi:"status"`
}

func (TokenReviewPatchTypeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*TokenReviewPatchType)(nil)).Elem()
}

func (i TokenReviewPatchTypeArgs) ToTokenReviewPatchTypeOutput() TokenReviewPatchTypeOutput {
	return i.ToTokenReviewPatchTypeOutputWithContext(context.Background())
}

func (i TokenReviewPatchTypeArgs) ToTokenReviewPatchTypeOutputWithContext(ctx context.Context) TokenReviewPatchTypeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TokenReviewPatchTypeOutput)
}

// TokenReview attempts to authenticate a token to a known user. Note: TokenReview requests may be cached by the webhook token authenticator plugin in the kube-apiserver.
type TokenReviewPatchTypeOutput struct{ *pulumi.OutputState }

func (TokenReviewPatchTypeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*TokenReviewPatchType)(nil)).Elem()
}

func (o TokenReviewPatchTypeOutput) ToTokenReviewPatchTypeOutput() TokenReviewPatchTypeOutput {
	return o
}

func (o TokenReviewPatchTypeOutput) ToTokenReviewPatchTypeOutputWithContext(ctx context.Context) TokenReviewPatchTypeOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o TokenReviewPatchTypeOutput) ApiVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v TokenReviewPatchType) *string { return v.ApiVersion }).(pulumi.StringPtrOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o TokenReviewPatchTypeOutput) Kind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v TokenReviewPatchType) *string { return v.Kind }).(pulumi.StringPtrOutput)
}

func (o TokenReviewPatchTypeOutput) Metadata() metav1.ObjectMetaPtrOutput {
	return o.ApplyT(func(v TokenReviewPatchType) *metav1.ObjectMeta { return v.Metadata }).(metav1.ObjectMetaPtrOutput)
}

// Spec holds information about the request being evaluated
func (o TokenReviewPatchTypeOutput) Spec() TokenReviewSpecPtrOutput {
	return o.ApplyT(func(v TokenReviewPatchType) *TokenReviewSpec { return v.Spec }).(TokenReviewSpecPtrOutput)
}

// Status is filled in by the server and indicates whether the request can be authenticated.
func (o TokenReviewPatchTypeOutput) Status() TokenReviewStatusPtrOutput {
	return o.ApplyT(func(v TokenReviewPatchType) *TokenReviewStatus { return v.Status }).(TokenReviewStatusPtrOutput)
}

// TokenReviewSpec is a description of the token authentication request.
type TokenReviewSpec struct {
	// Audiences is a list of the identifiers that the resource server presented with the token identifies as. Audience-aware token authenticators will verify that the token was intended for at least one of the audiences in this list. If no audiences are provided, the audience will default to the audience of the Kubernetes apiserver.
	Audiences []string `pulumi:"audiences"`
	// Token is the opaque bearer token.
	Token *string `pulumi:"token"`
}

// TokenReviewSpecInput is an input type that accepts TokenReviewSpecArgs and TokenReviewSpecOutput values.
// You can construct a concrete instance of `TokenReviewSpecInput` via:
//
//          TokenReviewSpecArgs{...}
type TokenReviewSpecInput interface {
	pulumi.Input

	ToTokenReviewSpecOutput() TokenReviewSpecOutput
	ToTokenReviewSpecOutputWithContext(context.Context) TokenReviewSpecOutput
}

// TokenReviewSpec is a description of the token authentication request.
type TokenReviewSpecArgs struct {
	// Audiences is a list of the identifiers that the resource server presented with the token identifies as. Audience-aware token authenticators will verify that the token was intended for at least one of the audiences in this list. If no audiences are provided, the audience will default to the audience of the Kubernetes apiserver.
	Audiences pulumi.StringArrayInput `pulumi:"audiences"`
	// Token is the opaque bearer token.
	Token pulumi.StringPtrInput `pulumi:"token"`
}

func (TokenReviewSpecArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*TokenReviewSpec)(nil)).Elem()
}

func (i TokenReviewSpecArgs) ToTokenReviewSpecOutput() TokenReviewSpecOutput {
	return i.ToTokenReviewSpecOutputWithContext(context.Background())
}

func (i TokenReviewSpecArgs) ToTokenReviewSpecOutputWithContext(ctx context.Context) TokenReviewSpecOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TokenReviewSpecOutput)
}

func (i TokenReviewSpecArgs) ToTokenReviewSpecPtrOutput() TokenReviewSpecPtrOutput {
	return i.ToTokenReviewSpecPtrOutputWithContext(context.Background())
}

func (i TokenReviewSpecArgs) ToTokenReviewSpecPtrOutputWithContext(ctx context.Context) TokenReviewSpecPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TokenReviewSpecOutput).ToTokenReviewSpecPtrOutputWithContext(ctx)
}

// TokenReviewSpecPtrInput is an input type that accepts TokenReviewSpecArgs, TokenReviewSpecPtr and TokenReviewSpecPtrOutput values.
// You can construct a concrete instance of `TokenReviewSpecPtrInput` via:
//
//          TokenReviewSpecArgs{...}
//
//  or:
//
//          nil
type TokenReviewSpecPtrInput interface {
	pulumi.Input

	ToTokenReviewSpecPtrOutput() TokenReviewSpecPtrOutput
	ToTokenReviewSpecPtrOutputWithContext(context.Context) TokenReviewSpecPtrOutput
}

type tokenReviewSpecPtrType TokenReviewSpecArgs

func TokenReviewSpecPtr(v *TokenReviewSpecArgs) TokenReviewSpecPtrInput {
	return (*tokenReviewSpecPtrType)(v)
}

func (*tokenReviewSpecPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**TokenReviewSpec)(nil)).Elem()
}

func (i *tokenReviewSpecPtrType) ToTokenReviewSpecPtrOutput() TokenReviewSpecPtrOutput {
	return i.ToTokenReviewSpecPtrOutputWithContext(context.Background())
}

func (i *tokenReviewSpecPtrType) ToTokenReviewSpecPtrOutputWithContext(ctx context.Context) TokenReviewSpecPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TokenReviewSpecPtrOutput)
}

// TokenReviewSpec is a description of the token authentication request.
type TokenReviewSpecOutput struct{ *pulumi.OutputState }

func (TokenReviewSpecOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*TokenReviewSpec)(nil)).Elem()
}

func (o TokenReviewSpecOutput) ToTokenReviewSpecOutput() TokenReviewSpecOutput {
	return o
}

func (o TokenReviewSpecOutput) ToTokenReviewSpecOutputWithContext(ctx context.Context) TokenReviewSpecOutput {
	return o
}

func (o TokenReviewSpecOutput) ToTokenReviewSpecPtrOutput() TokenReviewSpecPtrOutput {
	return o.ToTokenReviewSpecPtrOutputWithContext(context.Background())
}

func (o TokenReviewSpecOutput) ToTokenReviewSpecPtrOutputWithContext(ctx context.Context) TokenReviewSpecPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v TokenReviewSpec) *TokenReviewSpec {
		return &v
	}).(TokenReviewSpecPtrOutput)
}

// Audiences is a list of the identifiers that the resource server presented with the token identifies as. Audience-aware token authenticators will verify that the token was intended for at least one of the audiences in this list. If no audiences are provided, the audience will default to the audience of the Kubernetes apiserver.
func (o TokenReviewSpecOutput) Audiences() pulumi.StringArrayOutput {
	return o.ApplyT(func(v TokenReviewSpec) []string { return v.Audiences }).(pulumi.StringArrayOutput)
}

// Token is the opaque bearer token.
func (o TokenReviewSpecOutput) Token() pulumi.StringPtrOutput {
	return o.ApplyT(func(v TokenReviewSpec) *string { return v.Token }).(pulumi.StringPtrOutput)
}

type TokenReviewSpecPtrOutput struct{ *pulumi.OutputState }

func (TokenReviewSpecPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**TokenReviewSpec)(nil)).Elem()
}

func (o TokenReviewSpecPtrOutput) ToTokenReviewSpecPtrOutput() TokenReviewSpecPtrOutput {
	return o
}

func (o TokenReviewSpecPtrOutput) ToTokenReviewSpecPtrOutputWithContext(ctx context.Context) TokenReviewSpecPtrOutput {
	return o
}

func (o TokenReviewSpecPtrOutput) Elem() TokenReviewSpecOutput {
	return o.ApplyT(func(v *TokenReviewSpec) TokenReviewSpec {
		if v != nil {
			return *v
		}
		var ret TokenReviewSpec
		return ret
	}).(TokenReviewSpecOutput)
}

// Audiences is a list of the identifiers that the resource server presented with the token identifies as. Audience-aware token authenticators will verify that the token was intended for at least one of the audiences in this list. If no audiences are provided, the audience will default to the audience of the Kubernetes apiserver.
func (o TokenReviewSpecPtrOutput) Audiences() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *TokenReviewSpec) []string {
		if v == nil {
			return nil
		}
		return v.Audiences
	}).(pulumi.StringArrayOutput)
}

// Token is the opaque bearer token.
func (o TokenReviewSpecPtrOutput) Token() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TokenReviewSpec) *string {
		if v == nil {
			return nil
		}
		return v.Token
	}).(pulumi.StringPtrOutput)
}

// TokenReviewSpec is a description of the token authentication request.
type TokenReviewSpecPatch struct {
	// Audiences is a list of the identifiers that the resource server presented with the token identifies as. Audience-aware token authenticators will verify that the token was intended for at least one of the audiences in this list. If no audiences are provided, the audience will default to the audience of the Kubernetes apiserver.
	Audiences []string `pulumi:"audiences"`
	// Token is the opaque bearer token.
	Token *string `pulumi:"token"`
}

// TokenReviewSpecPatchInput is an input type that accepts TokenReviewSpecPatchArgs and TokenReviewSpecPatchOutput values.
// You can construct a concrete instance of `TokenReviewSpecPatchInput` via:
//
//          TokenReviewSpecPatchArgs{...}
type TokenReviewSpecPatchInput interface {
	pulumi.Input

	ToTokenReviewSpecPatchOutput() TokenReviewSpecPatchOutput
	ToTokenReviewSpecPatchOutputWithContext(context.Context) TokenReviewSpecPatchOutput
}

// TokenReviewSpec is a description of the token authentication request.
type TokenReviewSpecPatchArgs struct {
	// Audiences is a list of the identifiers that the resource server presented with the token identifies as. Audience-aware token authenticators will verify that the token was intended for at least one of the audiences in this list. If no audiences are provided, the audience will default to the audience of the Kubernetes apiserver.
	Audiences pulumi.StringArrayInput `pulumi:"audiences"`
	// Token is the opaque bearer token.
	Token pulumi.StringPtrInput `pulumi:"token"`
}

func (TokenReviewSpecPatchArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*TokenReviewSpecPatch)(nil)).Elem()
}

func (i TokenReviewSpecPatchArgs) ToTokenReviewSpecPatchOutput() TokenReviewSpecPatchOutput {
	return i.ToTokenReviewSpecPatchOutputWithContext(context.Background())
}

func (i TokenReviewSpecPatchArgs) ToTokenReviewSpecPatchOutputWithContext(ctx context.Context) TokenReviewSpecPatchOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TokenReviewSpecPatchOutput)
}

// TokenReviewSpec is a description of the token authentication request.
type TokenReviewSpecPatchOutput struct{ *pulumi.OutputState }

func (TokenReviewSpecPatchOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*TokenReviewSpecPatch)(nil)).Elem()
}

func (o TokenReviewSpecPatchOutput) ToTokenReviewSpecPatchOutput() TokenReviewSpecPatchOutput {
	return o
}

func (o TokenReviewSpecPatchOutput) ToTokenReviewSpecPatchOutputWithContext(ctx context.Context) TokenReviewSpecPatchOutput {
	return o
}

// Audiences is a list of the identifiers that the resource server presented with the token identifies as. Audience-aware token authenticators will verify that the token was intended for at least one of the audiences in this list. If no audiences are provided, the audience will default to the audience of the Kubernetes apiserver.
func (o TokenReviewSpecPatchOutput) Audiences() pulumi.StringArrayOutput {
	return o.ApplyT(func(v TokenReviewSpecPatch) []string { return v.Audiences }).(pulumi.StringArrayOutput)
}

// Token is the opaque bearer token.
func (o TokenReviewSpecPatchOutput) Token() pulumi.StringPtrOutput {
	return o.ApplyT(func(v TokenReviewSpecPatch) *string { return v.Token }).(pulumi.StringPtrOutput)
}

// TokenReviewStatus is the result of the token authentication request.
type TokenReviewStatus struct {
	// Audiences are audience identifiers chosen by the authenticator that are compatible with both the TokenReview and token. An identifier is any identifier in the intersection of the TokenReviewSpec audiences and the token's audiences. A client of the TokenReview API that sets the spec.audiences field should validate that a compatible audience identifier is returned in the status.audiences field to ensure that the TokenReview server is audience aware. If a TokenReview returns an empty status.audience field where status.authenticated is "true", the token is valid against the audience of the Kubernetes API server.
	Audiences []string `pulumi:"audiences"`
	// Authenticated indicates that the token was associated with a known user.
	Authenticated *bool `pulumi:"authenticated"`
	// Error indicates that the token couldn't be checked
	Error *string `pulumi:"error"`
	// User is the UserInfo associated with the provided token.
	User *UserInfo `pulumi:"user"`
}

// TokenReviewStatusInput is an input type that accepts TokenReviewStatusArgs and TokenReviewStatusOutput values.
// You can construct a concrete instance of `TokenReviewStatusInput` via:
//
//          TokenReviewStatusArgs{...}
type TokenReviewStatusInput interface {
	pulumi.Input

	ToTokenReviewStatusOutput() TokenReviewStatusOutput
	ToTokenReviewStatusOutputWithContext(context.Context) TokenReviewStatusOutput
}

// TokenReviewStatus is the result of the token authentication request.
type TokenReviewStatusArgs struct {
	// Audiences are audience identifiers chosen by the authenticator that are compatible with both the TokenReview and token. An identifier is any identifier in the intersection of the TokenReviewSpec audiences and the token's audiences. A client of the TokenReview API that sets the spec.audiences field should validate that a compatible audience identifier is returned in the status.audiences field to ensure that the TokenReview server is audience aware. If a TokenReview returns an empty status.audience field where status.authenticated is "true", the token is valid against the audience of the Kubernetes API server.
	Audiences pulumi.StringArrayInput `pulumi:"audiences"`
	// Authenticated indicates that the token was associated with a known user.
	Authenticated pulumi.BoolPtrInput `pulumi:"authenticated"`
	// Error indicates that the token couldn't be checked
	Error pulumi.StringPtrInput `pulumi:"error"`
	// User is the UserInfo associated with the provided token.
	User UserInfoPtrInput `pulumi:"user"`
}

func (TokenReviewStatusArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*TokenReviewStatus)(nil)).Elem()
}

func (i TokenReviewStatusArgs) ToTokenReviewStatusOutput() TokenReviewStatusOutput {
	return i.ToTokenReviewStatusOutputWithContext(context.Background())
}

func (i TokenReviewStatusArgs) ToTokenReviewStatusOutputWithContext(ctx context.Context) TokenReviewStatusOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TokenReviewStatusOutput)
}

func (i TokenReviewStatusArgs) ToTokenReviewStatusPtrOutput() TokenReviewStatusPtrOutput {
	return i.ToTokenReviewStatusPtrOutputWithContext(context.Background())
}

func (i TokenReviewStatusArgs) ToTokenReviewStatusPtrOutputWithContext(ctx context.Context) TokenReviewStatusPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TokenReviewStatusOutput).ToTokenReviewStatusPtrOutputWithContext(ctx)
}

// TokenReviewStatusPtrInput is an input type that accepts TokenReviewStatusArgs, TokenReviewStatusPtr and TokenReviewStatusPtrOutput values.
// You can construct a concrete instance of `TokenReviewStatusPtrInput` via:
//
//          TokenReviewStatusArgs{...}
//
//  or:
//
//          nil
type TokenReviewStatusPtrInput interface {
	pulumi.Input

	ToTokenReviewStatusPtrOutput() TokenReviewStatusPtrOutput
	ToTokenReviewStatusPtrOutputWithContext(context.Context) TokenReviewStatusPtrOutput
}

type tokenReviewStatusPtrType TokenReviewStatusArgs

func TokenReviewStatusPtr(v *TokenReviewStatusArgs) TokenReviewStatusPtrInput {
	return (*tokenReviewStatusPtrType)(v)
}

func (*tokenReviewStatusPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**TokenReviewStatus)(nil)).Elem()
}

func (i *tokenReviewStatusPtrType) ToTokenReviewStatusPtrOutput() TokenReviewStatusPtrOutput {
	return i.ToTokenReviewStatusPtrOutputWithContext(context.Background())
}

func (i *tokenReviewStatusPtrType) ToTokenReviewStatusPtrOutputWithContext(ctx context.Context) TokenReviewStatusPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TokenReviewStatusPtrOutput)
}

// TokenReviewStatus is the result of the token authentication request.
type TokenReviewStatusOutput struct{ *pulumi.OutputState }

func (TokenReviewStatusOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*TokenReviewStatus)(nil)).Elem()
}

func (o TokenReviewStatusOutput) ToTokenReviewStatusOutput() TokenReviewStatusOutput {
	return o
}

func (o TokenReviewStatusOutput) ToTokenReviewStatusOutputWithContext(ctx context.Context) TokenReviewStatusOutput {
	return o
}

func (o TokenReviewStatusOutput) ToTokenReviewStatusPtrOutput() TokenReviewStatusPtrOutput {
	return o.ToTokenReviewStatusPtrOutputWithContext(context.Background())
}

func (o TokenReviewStatusOutput) ToTokenReviewStatusPtrOutputWithContext(ctx context.Context) TokenReviewStatusPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v TokenReviewStatus) *TokenReviewStatus {
		return &v
	}).(TokenReviewStatusPtrOutput)
}

// Audiences are audience identifiers chosen by the authenticator that are compatible with both the TokenReview and token. An identifier is any identifier in the intersection of the TokenReviewSpec audiences and the token's audiences. A client of the TokenReview API that sets the spec.audiences field should validate that a compatible audience identifier is returned in the status.audiences field to ensure that the TokenReview server is audience aware. If a TokenReview returns an empty status.audience field where status.authenticated is "true", the token is valid against the audience of the Kubernetes API server.
func (o TokenReviewStatusOutput) Audiences() pulumi.StringArrayOutput {
	return o.ApplyT(func(v TokenReviewStatus) []string { return v.Audiences }).(pulumi.StringArrayOutput)
}

// Authenticated indicates that the token was associated with a known user.
func (o TokenReviewStatusOutput) Authenticated() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v TokenReviewStatus) *bool { return v.Authenticated }).(pulumi.BoolPtrOutput)
}

// Error indicates that the token couldn't be checked
func (o TokenReviewStatusOutput) Error() pulumi.StringPtrOutput {
	return o.ApplyT(func(v TokenReviewStatus) *string { return v.Error }).(pulumi.StringPtrOutput)
}

// User is the UserInfo associated with the provided token.
func (o TokenReviewStatusOutput) User() UserInfoPtrOutput {
	return o.ApplyT(func(v TokenReviewStatus) *UserInfo { return v.User }).(UserInfoPtrOutput)
}

type TokenReviewStatusPtrOutput struct{ *pulumi.OutputState }

func (TokenReviewStatusPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**TokenReviewStatus)(nil)).Elem()
}

func (o TokenReviewStatusPtrOutput) ToTokenReviewStatusPtrOutput() TokenReviewStatusPtrOutput {
	return o
}

func (o TokenReviewStatusPtrOutput) ToTokenReviewStatusPtrOutputWithContext(ctx context.Context) TokenReviewStatusPtrOutput {
	return o
}

func (o TokenReviewStatusPtrOutput) Elem() TokenReviewStatusOutput {
	return o.ApplyT(func(v *TokenReviewStatus) TokenReviewStatus {
		if v != nil {
			return *v
		}
		var ret TokenReviewStatus
		return ret
	}).(TokenReviewStatusOutput)
}

// Audiences are audience identifiers chosen by the authenticator that are compatible with both the TokenReview and token. An identifier is any identifier in the intersection of the TokenReviewSpec audiences and the token's audiences. A client of the TokenReview API that sets the spec.audiences field should validate that a compatible audience identifier is returned in the status.audiences field to ensure that the TokenReview server is audience aware. If a TokenReview returns an empty status.audience field where status.authenticated is "true", the token is valid against the audience of the Kubernetes API server.
func (o TokenReviewStatusPtrOutput) Audiences() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *TokenReviewStatus) []string {
		if v == nil {
			return nil
		}
		return v.Audiences
	}).(pulumi.StringArrayOutput)
}

// Authenticated indicates that the token was associated with a known user.
func (o TokenReviewStatusPtrOutput) Authenticated() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *TokenReviewStatus) *bool {
		if v == nil {
			return nil
		}
		return v.Authenticated
	}).(pulumi.BoolPtrOutput)
}

// Error indicates that the token couldn't be checked
func (o TokenReviewStatusPtrOutput) Error() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TokenReviewStatus) *string {
		if v == nil {
			return nil
		}
		return v.Error
	}).(pulumi.StringPtrOutput)
}

// User is the UserInfo associated with the provided token.
func (o TokenReviewStatusPtrOutput) User() UserInfoPtrOutput {
	return o.ApplyT(func(v *TokenReviewStatus) *UserInfo {
		if v == nil {
			return nil
		}
		return v.User
	}).(UserInfoPtrOutput)
}

// TokenReviewStatus is the result of the token authentication request.
type TokenReviewStatusPatch struct {
	// Audiences are audience identifiers chosen by the authenticator that are compatible with both the TokenReview and token. An identifier is any identifier in the intersection of the TokenReviewSpec audiences and the token's audiences. A client of the TokenReview API that sets the spec.audiences field should validate that a compatible audience identifier is returned in the status.audiences field to ensure that the TokenReview server is audience aware. If a TokenReview returns an empty status.audience field where status.authenticated is "true", the token is valid against the audience of the Kubernetes API server.
	Audiences []string `pulumi:"audiences"`
	// Authenticated indicates that the token was associated with a known user.
	Authenticated *bool `pulumi:"authenticated"`
	// Error indicates that the token couldn't be checked
	Error *string `pulumi:"error"`
	// User is the UserInfo associated with the provided token.
	User *UserInfo `pulumi:"user"`
}

// TokenReviewStatusPatchInput is an input type that accepts TokenReviewStatusPatchArgs and TokenReviewStatusPatchOutput values.
// You can construct a concrete instance of `TokenReviewStatusPatchInput` via:
//
//          TokenReviewStatusPatchArgs{...}
type TokenReviewStatusPatchInput interface {
	pulumi.Input

	ToTokenReviewStatusPatchOutput() TokenReviewStatusPatchOutput
	ToTokenReviewStatusPatchOutputWithContext(context.Context) TokenReviewStatusPatchOutput
}

// TokenReviewStatus is the result of the token authentication request.
type TokenReviewStatusPatchArgs struct {
	// Audiences are audience identifiers chosen by the authenticator that are compatible with both the TokenReview and token. An identifier is any identifier in the intersection of the TokenReviewSpec audiences and the token's audiences. A client of the TokenReview API that sets the spec.audiences field should validate that a compatible audience identifier is returned in the status.audiences field to ensure that the TokenReview server is audience aware. If a TokenReview returns an empty status.audience field where status.authenticated is "true", the token is valid against the audience of the Kubernetes API server.
	Audiences pulumi.StringArrayInput `pulumi:"audiences"`
	// Authenticated indicates that the token was associated with a known user.
	Authenticated pulumi.BoolPtrInput `pulumi:"authenticated"`
	// Error indicates that the token couldn't be checked
	Error pulumi.StringPtrInput `pulumi:"error"`
	// User is the UserInfo associated with the provided token.
	User UserInfoPtrInput `pulumi:"user"`
}

func (TokenReviewStatusPatchArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*TokenReviewStatusPatch)(nil)).Elem()
}

func (i TokenReviewStatusPatchArgs) ToTokenReviewStatusPatchOutput() TokenReviewStatusPatchOutput {
	return i.ToTokenReviewStatusPatchOutputWithContext(context.Background())
}

func (i TokenReviewStatusPatchArgs) ToTokenReviewStatusPatchOutputWithContext(ctx context.Context) TokenReviewStatusPatchOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TokenReviewStatusPatchOutput)
}

// TokenReviewStatus is the result of the token authentication request.
type TokenReviewStatusPatchOutput struct{ *pulumi.OutputState }

func (TokenReviewStatusPatchOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*TokenReviewStatusPatch)(nil)).Elem()
}

func (o TokenReviewStatusPatchOutput) ToTokenReviewStatusPatchOutput() TokenReviewStatusPatchOutput {
	return o
}

func (o TokenReviewStatusPatchOutput) ToTokenReviewStatusPatchOutputWithContext(ctx context.Context) TokenReviewStatusPatchOutput {
	return o
}

// Audiences are audience identifiers chosen by the authenticator that are compatible with both the TokenReview and token. An identifier is any identifier in the intersection of the TokenReviewSpec audiences and the token's audiences. A client of the TokenReview API that sets the spec.audiences field should validate that a compatible audience identifier is returned in the status.audiences field to ensure that the TokenReview server is audience aware. If a TokenReview returns an empty status.audience field where status.authenticated is "true", the token is valid against the audience of the Kubernetes API server.
func (o TokenReviewStatusPatchOutput) Audiences() pulumi.StringArrayOutput {
	return o.ApplyT(func(v TokenReviewStatusPatch) []string { return v.Audiences }).(pulumi.StringArrayOutput)
}

// Authenticated indicates that the token was associated with a known user.
func (o TokenReviewStatusPatchOutput) Authenticated() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v TokenReviewStatusPatch) *bool { return v.Authenticated }).(pulumi.BoolPtrOutput)
}

// Error indicates that the token couldn't be checked
func (o TokenReviewStatusPatchOutput) Error() pulumi.StringPtrOutput {
	return o.ApplyT(func(v TokenReviewStatusPatch) *string { return v.Error }).(pulumi.StringPtrOutput)
}

// User is the UserInfo associated with the provided token.
func (o TokenReviewStatusPatchOutput) User() UserInfoPtrOutput {
	return o.ApplyT(func(v TokenReviewStatusPatch) *UserInfo { return v.User }).(UserInfoPtrOutput)
}

// UserInfo holds the information about the user needed to implement the user.Info interface.
type UserInfo struct {
	// Any additional information provided by the authenticator.
	Extra map[string][]string `pulumi:"extra"`
	// The names of groups this user is a part of.
	Groups []string `pulumi:"groups"`
	// A unique value that identifies this user across time. If this user is deleted and another user by the same name is added, they will have different UIDs.
	Uid *string `pulumi:"uid"`
	// The name that uniquely identifies this user among all active users.
	Username *string `pulumi:"username"`
}

// UserInfoInput is an input type that accepts UserInfoArgs and UserInfoOutput values.
// You can construct a concrete instance of `UserInfoInput` via:
//
//          UserInfoArgs{...}
type UserInfoInput interface {
	pulumi.Input

	ToUserInfoOutput() UserInfoOutput
	ToUserInfoOutputWithContext(context.Context) UserInfoOutput
}

// UserInfo holds the information about the user needed to implement the user.Info interface.
type UserInfoArgs struct {
	// Any additional information provided by the authenticator.
	Extra pulumi.StringArrayMapInput `pulumi:"extra"`
	// The names of groups this user is a part of.
	Groups pulumi.StringArrayInput `pulumi:"groups"`
	// A unique value that identifies this user across time. If this user is deleted and another user by the same name is added, they will have different UIDs.
	Uid pulumi.StringPtrInput `pulumi:"uid"`
	// The name that uniquely identifies this user among all active users.
	Username pulumi.StringPtrInput `pulumi:"username"`
}

func (UserInfoArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*UserInfo)(nil)).Elem()
}

func (i UserInfoArgs) ToUserInfoOutput() UserInfoOutput {
	return i.ToUserInfoOutputWithContext(context.Background())
}

func (i UserInfoArgs) ToUserInfoOutputWithContext(ctx context.Context) UserInfoOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserInfoOutput)
}

func (i UserInfoArgs) ToUserInfoPtrOutput() UserInfoPtrOutput {
	return i.ToUserInfoPtrOutputWithContext(context.Background())
}

func (i UserInfoArgs) ToUserInfoPtrOutputWithContext(ctx context.Context) UserInfoPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserInfoOutput).ToUserInfoPtrOutputWithContext(ctx)
}

// UserInfoPtrInput is an input type that accepts UserInfoArgs, UserInfoPtr and UserInfoPtrOutput values.
// You can construct a concrete instance of `UserInfoPtrInput` via:
//
//          UserInfoArgs{...}
//
//  or:
//
//          nil
type UserInfoPtrInput interface {
	pulumi.Input

	ToUserInfoPtrOutput() UserInfoPtrOutput
	ToUserInfoPtrOutputWithContext(context.Context) UserInfoPtrOutput
}

type userInfoPtrType UserInfoArgs

func UserInfoPtr(v *UserInfoArgs) UserInfoPtrInput {
	return (*userInfoPtrType)(v)
}

func (*userInfoPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**UserInfo)(nil)).Elem()
}

func (i *userInfoPtrType) ToUserInfoPtrOutput() UserInfoPtrOutput {
	return i.ToUserInfoPtrOutputWithContext(context.Background())
}

func (i *userInfoPtrType) ToUserInfoPtrOutputWithContext(ctx context.Context) UserInfoPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserInfoPtrOutput)
}

// UserInfo holds the information about the user needed to implement the user.Info interface.
type UserInfoOutput struct{ *pulumi.OutputState }

func (UserInfoOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*UserInfo)(nil)).Elem()
}

func (o UserInfoOutput) ToUserInfoOutput() UserInfoOutput {
	return o
}

func (o UserInfoOutput) ToUserInfoOutputWithContext(ctx context.Context) UserInfoOutput {
	return o
}

func (o UserInfoOutput) ToUserInfoPtrOutput() UserInfoPtrOutput {
	return o.ToUserInfoPtrOutputWithContext(context.Background())
}

func (o UserInfoOutput) ToUserInfoPtrOutputWithContext(ctx context.Context) UserInfoPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v UserInfo) *UserInfo {
		return &v
	}).(UserInfoPtrOutput)
}

// Any additional information provided by the authenticator.
func (o UserInfoOutput) Extra() pulumi.StringArrayMapOutput {
	return o.ApplyT(func(v UserInfo) map[string][]string { return v.Extra }).(pulumi.StringArrayMapOutput)
}

// The names of groups this user is a part of.
func (o UserInfoOutput) Groups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v UserInfo) []string { return v.Groups }).(pulumi.StringArrayOutput)
}

// A unique value that identifies this user across time. If this user is deleted and another user by the same name is added, they will have different UIDs.
func (o UserInfoOutput) Uid() pulumi.StringPtrOutput {
	return o.ApplyT(func(v UserInfo) *string { return v.Uid }).(pulumi.StringPtrOutput)
}

// The name that uniquely identifies this user among all active users.
func (o UserInfoOutput) Username() pulumi.StringPtrOutput {
	return o.ApplyT(func(v UserInfo) *string { return v.Username }).(pulumi.StringPtrOutput)
}

type UserInfoPtrOutput struct{ *pulumi.OutputState }

func (UserInfoPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**UserInfo)(nil)).Elem()
}

func (o UserInfoPtrOutput) ToUserInfoPtrOutput() UserInfoPtrOutput {
	return o
}

func (o UserInfoPtrOutput) ToUserInfoPtrOutputWithContext(ctx context.Context) UserInfoPtrOutput {
	return o
}

func (o UserInfoPtrOutput) Elem() UserInfoOutput {
	return o.ApplyT(func(v *UserInfo) UserInfo {
		if v != nil {
			return *v
		}
		var ret UserInfo
		return ret
	}).(UserInfoOutput)
}

// Any additional information provided by the authenticator.
func (o UserInfoPtrOutput) Extra() pulumi.StringArrayMapOutput {
	return o.ApplyT(func(v *UserInfo) map[string][]string {
		if v == nil {
			return nil
		}
		return v.Extra
	}).(pulumi.StringArrayMapOutput)
}

// The names of groups this user is a part of.
func (o UserInfoPtrOutput) Groups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *UserInfo) []string {
		if v == nil {
			return nil
		}
		return v.Groups
	}).(pulumi.StringArrayOutput)
}

// A unique value that identifies this user across time. If this user is deleted and another user by the same name is added, they will have different UIDs.
func (o UserInfoPtrOutput) Uid() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *UserInfo) *string {
		if v == nil {
			return nil
		}
		return v.Uid
	}).(pulumi.StringPtrOutput)
}

// The name that uniquely identifies this user among all active users.
func (o UserInfoPtrOutput) Username() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *UserInfo) *string {
		if v == nil {
			return nil
		}
		return v.Username
	}).(pulumi.StringPtrOutput)
}

// UserInfo holds the information about the user needed to implement the user.Info interface.
type UserInfoPatch struct {
	// Any additional information provided by the authenticator.
	Extra map[string][]string `pulumi:"extra"`
	// The names of groups this user is a part of.
	Groups []string `pulumi:"groups"`
	// A unique value that identifies this user across time. If this user is deleted and another user by the same name is added, they will have different UIDs.
	Uid *string `pulumi:"uid"`
	// The name that uniquely identifies this user among all active users.
	Username *string `pulumi:"username"`
}

// UserInfoPatchInput is an input type that accepts UserInfoPatchArgs and UserInfoPatchOutput values.
// You can construct a concrete instance of `UserInfoPatchInput` via:
//
//          UserInfoPatchArgs{...}
type UserInfoPatchInput interface {
	pulumi.Input

	ToUserInfoPatchOutput() UserInfoPatchOutput
	ToUserInfoPatchOutputWithContext(context.Context) UserInfoPatchOutput
}

// UserInfo holds the information about the user needed to implement the user.Info interface.
type UserInfoPatchArgs struct {
	// Any additional information provided by the authenticator.
	Extra pulumi.StringArrayMapInput `pulumi:"extra"`
	// The names of groups this user is a part of.
	Groups pulumi.StringArrayInput `pulumi:"groups"`
	// A unique value that identifies this user across time. If this user is deleted and another user by the same name is added, they will have different UIDs.
	Uid pulumi.StringPtrInput `pulumi:"uid"`
	// The name that uniquely identifies this user among all active users.
	Username pulumi.StringPtrInput `pulumi:"username"`
}

func (UserInfoPatchArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*UserInfoPatch)(nil)).Elem()
}

func (i UserInfoPatchArgs) ToUserInfoPatchOutput() UserInfoPatchOutput {
	return i.ToUserInfoPatchOutputWithContext(context.Background())
}

func (i UserInfoPatchArgs) ToUserInfoPatchOutputWithContext(ctx context.Context) UserInfoPatchOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserInfoPatchOutput)
}

// UserInfo holds the information about the user needed to implement the user.Info interface.
type UserInfoPatchOutput struct{ *pulumi.OutputState }

func (UserInfoPatchOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*UserInfoPatch)(nil)).Elem()
}

func (o UserInfoPatchOutput) ToUserInfoPatchOutput() UserInfoPatchOutput {
	return o
}

func (o UserInfoPatchOutput) ToUserInfoPatchOutputWithContext(ctx context.Context) UserInfoPatchOutput {
	return o
}

// Any additional information provided by the authenticator.
func (o UserInfoPatchOutput) Extra() pulumi.StringArrayMapOutput {
	return o.ApplyT(func(v UserInfoPatch) map[string][]string { return v.Extra }).(pulumi.StringArrayMapOutput)
}

// The names of groups this user is a part of.
func (o UserInfoPatchOutput) Groups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v UserInfoPatch) []string { return v.Groups }).(pulumi.StringArrayOutput)
}

// A unique value that identifies this user across time. If this user is deleted and another user by the same name is added, they will have different UIDs.
func (o UserInfoPatchOutput) Uid() pulumi.StringPtrOutput {
	return o.ApplyT(func(v UserInfoPatch) *string { return v.Uid }).(pulumi.StringPtrOutput)
}

// The name that uniquely identifies this user among all active users.
func (o UserInfoPatchOutput) Username() pulumi.StringPtrOutput {
	return o.ApplyT(func(v UserInfoPatch) *string { return v.Username }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TokenReviewTypeInput)(nil)).Elem(), TokenReviewTypeArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*TokenReviewPatchTypeInput)(nil)).Elem(), TokenReviewPatchTypeArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*TokenReviewSpecInput)(nil)).Elem(), TokenReviewSpecArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*TokenReviewSpecPtrInput)(nil)).Elem(), TokenReviewSpecArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*TokenReviewSpecPatchInput)(nil)).Elem(), TokenReviewSpecPatchArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*TokenReviewStatusInput)(nil)).Elem(), TokenReviewStatusArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*TokenReviewStatusPtrInput)(nil)).Elem(), TokenReviewStatusArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*TokenReviewStatusPatchInput)(nil)).Elem(), TokenReviewStatusPatchArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*UserInfoInput)(nil)).Elem(), UserInfoArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*UserInfoPtrInput)(nil)).Elem(), UserInfoArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*UserInfoPatchInput)(nil)).Elem(), UserInfoPatchArgs{})
	pulumi.RegisterOutputType(TokenReviewTypeOutput{})
	pulumi.RegisterOutputType(TokenReviewPatchTypeOutput{})
	pulumi.RegisterOutputType(TokenReviewSpecOutput{})
	pulumi.RegisterOutputType(TokenReviewSpecPtrOutput{})
	pulumi.RegisterOutputType(TokenReviewSpecPatchOutput{})
	pulumi.RegisterOutputType(TokenReviewStatusOutput{})
	pulumi.RegisterOutputType(TokenReviewStatusPtrOutput{})
	pulumi.RegisterOutputType(TokenReviewStatusPatchOutput{})
	pulumi.RegisterOutputType(UserInfoOutput{})
	pulumi.RegisterOutputType(UserInfoPtrOutput{})
	pulumi.RegisterOutputType(UserInfoPatchOutput{})
}
